In [58]:
print("Dataset Shape")

Dataset Shape


In [59]:
import pandas as pd
file_path = '/kaggle/input/datasets/fahim173/stroke-risk/stroke_risk_prediction_dataset (1).csv'
df.head(25000)


,Age,Gender,Country,Height_cm,Weight_kg,BMI,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Heart_Rate,Blood_Glucose,...,Medication_Adherence,Exercise_Hours_Per_Week,Daily_Walking_Minutes,Work_Type,Residence_Type,Air_Pollution_Exposure,Stroke_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Stroke_Risk
0,80.0,Male,China,145.2,69.3,32.9,112,82,109,132.2,...,Excellent,NaN,79.0,Retired,Urban,High,47,Exercise Regularly,Yes,Moderate
1,37.0,Female,United Kingdom,188.6,110.8,31.1,137,76,59,187.5,...,Average,0.6,48.0,Student,Rural,Medium,40,Improve Diet Quality,Yes,Moderate
2,85.0,Female,Germany,175.5,103.7,33.7,108,105,89,196.4,...,Poor,1.7,114.0,Private,Rural,Medium,76,Monitor Blood Glucose Daily,Yes,High
3,44.0,Other,Brazil,161.3,50.2,19.3,126,73,88,209.1,...,Poor,1.5,101.0,Retired,Rural,Low,40,Exercise Regularly,Yes,Moderate
4,52.0,Female,United States,162.8,103.6,39.1,115,60,70,88.6,...,Average,7.1,55.0,Government,Rural,Medium,38,Monitor Blood Pressure,Yes,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,58.0,Male,Australia,148.9,122.0,55.0,113,76,106,121.2,...,Excellent,2.9,53.0,Private,Urban,Medium,53,Monitor Blood Pressure,Yes,Moderate
24996,81.0,Female,Canada,180.3,68.6,21.1,127,102,110,165.0,...,Excellent,6.0,NaN,Student,Rural,Medium,54,Exercise Regularly,Yes,Moderate
24997,79.0,Female,Germany,168.4,87.1,30.7,157,61,55,79.1,...,Poor,7.7,106.0,Retired,Urban,Medium,52,Improve Diet Quality,Yes,Moderate
24998,21.0,Female,China,NaN,45.9,21.5,142,84,79,154.9,...,Poor,8.5,16.0,Self-Employed,Rural,Low,42,Monitor Blood Pressure,Yes,Moderate


In [60]:
import pandas as pd
import numpy as np

# Load dataset
file_path = '/kaggle/input/datasets/fahim173/stroke-risk/stroke_risk_prediction_dataset (1).csv'
df = pd.read_csv(file_path)

# Drop identifier column if present as it has no predictive power
if 'Patient_ID' in df.columns:
    df = df.drop(columns=['Patient_ID'])

# Define target variable and feature set
target_col = 'Stroke_Risk'
X = df.drop(columns=[target_col])
y = df[target_col]

print(f"Dataset Shape: {df.shape}")
print(f"Features: {X.shape[1]} columns | Target: {target_col}")

Dataset Shape: (50000, 39)
Features: 38 columns | Target: Stroke_Risk


In [61]:
print("Check Missing Values & Average Missing Percentage")

Check Missing Values & Average Missing Percentage


In [62]:
import pandas as pd
import numpy as np

# Load dataset
file_path = '/kaggle/input/datasets/fahim173/stroke-risk/stroke_risk_prediction_dataset (1).csv'
df = pd.read_csv(file_path)

# Drop identifier column if present as it has no predictive power
if 'Patient_ID' in df.columns:
    df = df.drop(columns=['Patient_ID'])

# Define target variable and feature set
target_col = 'Stroke_Risk'
X = df.drop(columns=[target_col])
y = df[target_col]

print(f"Dataset Shape: {df.shape}")
print(f"Features: {X.shape[1]} columns | Target: {target_col}")

Dataset Shape: (50000, 39)
Features: 38 columns | Target: Stroke_Risk


In [63]:
# Calculate count and percentage of missing values
missing_count = X.isnull().sum()
missing_pct = (X.isnull().mean()) * 100

# Create summary DataFrame
missing_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing Percentage (%)': missing_pct
})

# Display features with missing values
print("--- Missing Values Summary ---")
print(missing_summary[missing_summary['Missing Count'] > 0].sort_values(by='Missing Percentage (%)', ascending=False))

--- Missing Values Summary ---
                         Missing Count  Missing Percentage (%)
Height_cm                         1525                   3.050
Weight_kg                         1523                   3.046
Exercise_Hours_Per_Week           1054                   2.108
Medication_Adherence              1051                   2.102
Daily_Walking_Minutes             1051                   2.102
LDL                               1050                   2.100
Triglycerides                     1032                   2.064
Sleep_Hours                       1026                   2.052
HDL                               1021                   2.042
HbA1c                             1006                   2.012
Total_Cholesterol                 1004                   2.008
Blood_Glucose                      960                   1.920
Age                                219                   0.438


In [64]:
# Identify columns with > 20% missing values
high_missing_cols = missing_pct[missing_pct > 20].index.tolist()

print(f"Columns to drop (> 20% missing): {high_missing_cols}")

# Drop identified columns
X = X.drop(columns=high_missing_cols)

Columns to drop (> 20% missing): []


In [65]:
# Identify columns with > 20% missing values
high_missing_cols = missing_pct[missing_pct > 20].index.tolist()

print(f"Columns to drop (> 20% missing): {high_missing_cols}")

# Drop identified columns
X = X.drop(columns=high_missing_cols)

Columns to drop (> 20% missing): []


In [66]:
# Impute numerical features with median and categorical features with mode
for col in X.columns:
    if X[col].isnull().sum() > 0:
        if X[col].dtype in ['float64', 'int64']:
            X[col] = X[col].fillna(X[col].median())
        else:
            X[col] = X[col].fillna(X[col].mode()[0])

print("Imputation completed.")

Imputation completed.


In [67]:
# Final verification of missing values
total_missing = X.isnull().sum().sum()
print(f"Total missing values remaining in features: {total_missing}")

Total missing values remaining in features: 0


In [68]:
from sklearn.preprocessing import LabelEncoder

# Encode categorical feature columns
label_encoders = {}
X_encoded = X.copy()

categorical_cols = X_encoded.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
    le = LabelEncoder()
    X_encoded[col] = le.fit_transform(X_encoded[col])
    label_encoders[col] = le

# Encode target variable
le_y = LabelEncoder()
y_encoded = le_y.fit_transform(y)

print("Label Encoding finished. Dataset is ready for model fitting.")

Label Encoding finished. Dataset is ready for model fitting.


In [69]:
from sklearn.model_selection import train_test_split

# 80/20 train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, 
    y_encoded, 
    test_size=0.20, 
    random_state=42, 
    stratify=y_encoded
)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape:  {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape:  {y_test.shape}")

X_train shape: (40000, 38)
X_test shape:  (10000, 38)
y_train shape: (40000,)
y_test shape:  (10000,)


In [70]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize and train Gaussian Naive Bayes classifier
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Predictions
y_pred = nb_model.predict(X_test)

# Evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
print("Naive Bayes Accuracy:", round(accuracy * 100, 2), "%")

print("--- Classification Report ---")
print(classification_report(y_test, y_pred, target_names=le_y.classes_))

print("--- Confusion Matrix ---")
print(confusion_matrix(y_test, y_pred))

Naive Bayes Accuracy: 82.86 %
--- Classification Report ---
              precision    recall  f1-score   support

        High       0.61      1.00      0.76      2422
         Low       0.85      0.95      0.89       703
    Moderate       0.99      0.76      0.86      6875

    accuracy                           0.83     10000
   macro avg       0.82      0.90      0.84     10000
weighted avg       0.89      0.83      0.84     10000

--- Confusion Matrix ---
[[2422    0    0]
 [   0  666   37]
 [1555  122 5198]]


In [71]:
# Merge features and encoded target to calculate Pearson correlation
df_encoded = X_encoded.copy()
df_encoded['Target'] = y_encoded

# Pearson correlation with target
pearson_corr = df_encoded.corr(method='pearson')['Target'].drop('Target').sort_values(ascending=False)

print("--- Pearson Correlation with Target (Top 10 Positively Correlated) ---")
print(pearson_corr.head(10))

--- Pearson Correlation with Target (Top 10 Positively Correlated) ---
AI_Health_Recommendation    0.249764
Smoking_Status              0.090248
Alcohol_Consumption         0.086517
Stress_Level                0.083577
HDL                         0.049297
Air_Pollution_Exposure      0.045014
Sleep_Hours                 0.041534
Daily_Walking_Minutes       0.027619
Height_cm                   0.023148
Exercise_Hours_Per_Week     0.022682
Name: Target, dtype: float64


In [72]:
from sklearn.naive_bayes import GaussianNB

# Create the Naive Bayes model
nb_model = GaussianNB()

# Fit the model using training data
nb_model.fit(X_train, y_train)

print("Naive Bayes model trained successfully!")

# Predict the target values for the test set
y_pred = nb_model.predict(X_test)

print("Predictions:")
print(y_pred[:10])

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Naive Bayes Accuracy:", round(accuracy * 100, 2), "%")

Naive Bayes model trained successfully!
Predictions:
[2 2 0 2 0 0 2 0 0 0]
Naive Bayes Accuracy: 82.86 %
